#应用
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  #名称
  name: {project}
  #命名空间
  namespace: {namespace}
spec:
  #启动应用数量
  replicas: 1
  #从容器启动到应用正常提供服务
  minReadySeconds: 10
  #策略
  strategy:
    #更新类型
    type: RollingUpdate
    #滚动更新
    rollingUpdate:
      #更新时允许最大激增的容器数
      maxSurge: 1
      #更新时允许最大 unavailable 容器数
      maxUnavailable: 0
  #模板
  template:
    #数据描述[元数据]
    metadata:
      #标签
      labels:
        #应用
        app: {project}
        #版本
        version: {version}
    #规格
    spec:



      #容器拉取权限
      imagePullSecrets:
        - name : {registryKey}
      #容器
      containers:
        #名称
      - name: {project}
        #镜像
        image: {img}
        #镜像挂载目录
        volumeMounts:
        - name: time
          mountPath: /etc/localtime
        #计算资源配置
        resources:
          #启动限制
          requests:
            #初始化CPU用量
            cpu: "100m"
            #初始化内存用量
            memory: "128Mi"
          #最大限制
          limits:
            #限制CPU最大用量
            cpu: "{cpu}"
            #限制内存最大用量
            memory: "{memory}"
        #环境变量
        env:
        #堆内存
        - name: heap
        #堆内存值,例子128m
          value: "{heap}"
        #存活探针
        livenessProbe:
          #get方式
          httpGet:
            #检测链接
            path: {k8sWorkingCheck}
            #端口
            port: 80
            #方式
            scheme: HTTP
          #初始化
          initialDelaySeconds: 60
          #检测间隔
          periodSeconds: 5
          #超时时间
          timeoutSeconds: 5
          #应用错误判定次数
          failureThreshold: 3
      #实际目录挂载
      volumes:
      - name: time
        hostPath:
          path: /etc/localtime